# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'result.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pylearn = QtWidgets.QLabel(self.centralwidget)
        self.pylearn.setGeometry(QtCore.QRect(10, 30, 90, 20))
        self.pylearn.setObjectName("pylearn")
        self.path_lbl = QtWidgets.QLabel(self.centralwidget)
        self.path_lbl.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.path_lbl.setObjectName("path_lbl")
        self.task_lbl = QtWidgets.QLabel(self.centralwidget)
        self.task_lbl.setGeometry(QtCore.QRect(240, 60, 47, 13))
        self.task_lbl.setObjectName("task_lbl")
        self.profile = QtWidgets.QLabel(self.centralwidget)
        self.profile.setGeometry(QtCore.QRect(450, 30, 47, 13))
        self.profile.setObjectName("profile")
        self.rating = QtWidgets.QLabel(self.centralwidget)
        self.rating.setGeometry(QtCore.QRect(510, 30, 47, 13))
        self.rating.setObjectName("rating")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(526, 60, 75, 23))
        self.back_btn.setObjectName("back_btn")
        self.answer_lbl = QtWidgets.QLabel(self.centralwidget)
        self.answer_lbl.setGeometry(QtCore.QRect(194, 90, 150, 20))
        self.answer_lbl.setObjectName("answer_lbl")
        self.submit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.submit_btn.setGeometry(QtCore.QRect(520, 530, 75, 23))
        self.submit_btn.setObjectName("submit_btn")
        self.results = QtWidgets.QScrollArea(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(40, 129, 521, 361))
        #self.results.setWidgetResizable(True)
        self.results.setObjectName("results")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.results.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSignOut = QtWidgets.QAction(MainWindow)        
        self.actionSignOut.setObjectName("actionSignOut")
        self.menuMenu.addAction(self.actionSignOut)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.actionSignOut.setText('Signout')
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())
        for btn in [self.submit_btn,self.back_btn]:
            btn.setStyleSheet("QPushButton {background-color: black; color: white;font-family='Times-Italic'}")
        self.task_lbl.setStyleSheet("font-family:'Californian FB';font-size:9pt;font-weight: bold; border-style:solid;border-width:1px;background-color:white;")
        self.path_lbl.setStyleSheet("font-family:'Californian FB';font-size:9pt;font-weight: bold; border-style:solid;border-width:1px;background-color:white;")
        self.answer_lbl.setStyleSheet("font-family:'Arial Black';font-size:10pt;font-weight: bold; border-style:solid;border-width:1px;background-color:white;")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pylearn.setText(_translate("MainWindow", "PYLEARN"))
        self.path_lbl.setText(_translate("MainWindow", "path"))
        self.task_lbl.setText(_translate("MainWindow", "task"))
        self.profile.setText(_translate("MainWindow", "username"))
        self.rating.setText(_translate("MainWindow", "0.0 ★"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.answer_lbl.setText(_translate("MainWindow", "Running TestCases"))
        self.submit_btn.setText(_translate("MainWindow", "Submit"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
