# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pylearn = QtWidgets.QLabel(self.centralwidget)
        self.pylearn.setGeometry(QtCore.QRect(280, 170, 90, 20))
        self.pylearn.setObjectName("pylearn")
        self.name_lbl = QtWidgets.QLabel(self.centralwidget)
        self.name_lbl.setGeometry(QtCore.QRect(210, 240, 47, 13))
        self.name_lbl.setObjectName("name_lbl")
        self.username_lbl = QtWidgets.QLabel(self.centralwidget)
        self.username_lbl.setGeometry(QtCore.QRect(210, 270, 47, 13))
        self.username_lbl.setObjectName("username_lbl")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(280, 240, 113, 20))
        self.name.setObjectName("name")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(280, 270, 113, 20))
        self.username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username.setObjectName("username")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(270, 350, 75, 23))
        self.create_btn.setObjectName("create_btn")
        self.password_lbl = QtWidgets.QLabel(self.centralwidget)
        self.password_lbl.setGeometry(QtCore.QRect(210, 300, 47, 13))
        self.password_lbl.setObjectName("password_lbl")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(280, 300, 113, 20))
        self.password.setObjectName("password")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(270, 385, 75, 23))
        self.login_btn.setObjectName("login_btn")
        self.login_btn.setText("login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 200, 111, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())
        
        self.pylearn.setFont(QtGui.QFont('72 Condensed', 15,weight=QtGui.QFont.Bold))   
        for label in [self.username_lbl,self.password_lbl,self.name_lbl]:
            label.setFont(QtGui.QFont('Calibri Light',10))
        for value in [self.username,self.password,self.name]:
            value.setStyleSheet("background-color:white;font-family='Times-Italic'")
        self.create_btn.setStyleSheet("QPushButton {background-color: black; color: white;font-family='Times-Italic'}")
        self.login_btn.setStyleSheet("QPushButton {background-color: black; color: white;font-family='Times-Italic'}")
        self.label.setFont(QtGui.QFont('Courier',9))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pylearn.setText(_translate("MainWindow", "PYLEARN"))
        self.name_lbl.setText(_translate("MainWindow", "Name"))
        self.username_lbl.setText(_translate("MainWindow", "Username"))
        self.create_btn.setText(_translate("MainWindow", "create"))
        self.password_lbl.setText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "CREATE ACCOUNT"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
